In [25]:
!pip uninstall torch

Found existing installation: torch 1.12.1+cu113
Uninstalling torch-1.12.1+cu113:
  Would remove:
    /usr/local/bin/convert-caffe2-to-onnx
    /usr/local/bin/convert-onnx-to-caffe2
    /usr/local/bin/torchrun
    /usr/local/lib/python3.7/dist-packages/caffe2/*
    /usr/local/lib/python3.7/dist-packages/torch-1.12.1+cu113.dist-info/*
    /usr/local/lib/python3.7/dist-packages/torch/*
    /usr/local/lib/python3.7/dist-packages/torchgen/*
Proceed (y/n)? y
  Successfully uninstalled torch-1.12.1+cu113


In [5]:
!pip install torch==1.8

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 735.5 MB 12 kB/s 
  Attempting uninstall: torch
    Found existing installation: torch 1.7.0
    Uninstalling torch-1.7.0:
      Successfully uninstalled torch-1.7.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.13.1+cu113 requires torch==1.12.1, but you have torch 1.8.0 which is incompatible.
torchtext 0.13.1 requires torch==1.12.1, but you have torch 1.8.0 which is incompatible.
torchaudio 0.12.1+cu113 requires torch==1.12.1, but you have torch 1.8.0 which is incompatible.
gpytorch 1.8.1 requires torch>=1.10, but you have torch 1.8.0 which is incompatible.


In [21]:
!pip uninstall gpytorch

Found existing installation: gpytorch 1.8.1
Uninstalling gpytorch-1.8.1:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/gpytorch-1.8.1.dist-info/*
    /usr/local/lib/python3.7/dist-packages/gpytorch/*
Proceed (y/n)? y
  Successfully uninstalled gpytorch-1.8.1


In [16]:
# !git clone https://github.com/RaulAstudillo06/BudgetedBO.git
%cd BudgetedBO/experiments
# !pip install botorch==0.5.0
# !pip install scikit-learn==0.21.3

/content/BudgetedBO/experiments


In [40]:
# !pip install timm==0.4.12

!python ackley_runner.py 0 60

tensor([[0.4751, 0.5925],
        [0.5788, 0.0371],
        [0.9507, 0.8623],
        [0.1205, 0.2614],
        [0.2149, 0.9742],
        [0.8538, 0.4035],
        [0.7421, 0.6955],
        [0.3142, 0.1725]])
tensor([-1.2906, -3.1490, -4.3481, -4.4727, -4.5936, -3.6443, -3.9902, -4.2046])
tensor([0.8157, 0.6008, 1.3642, 2.2022, 0.5105, 0.3513, 3.0149, 1.0932])
Problem: ackley
Sampling policy: B-MS-EI_1_1_60
Trial: 0
Iteration: 1
/usr/local/lib/python3.7/dist-packages/botorch/fit.py:111: BotorchWarning: Failed to convert ModelList to batched model. Performing joint instead of sequential fitting.
  warnings.warn(FAILED_CONVERSION_MSG, BotorchWarning)
/usr/local/lib/python3.7/dist-packages/botorch/models/gpytorch.py:89: BotorchTensorDimensionWarning: Non-strict enforcement of botorch tensor conventions. Ensure that target tensors Y has an explicit output dimension.
  BotorchTensorDimensionWarning,
/usr/local/lib/python3.7/dist-packages/botorch/models/gpytorch.py:89: BotorchTensorDimension